services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  UniversityOfCopenhagen\kuRecentContentBackendModule\:
    resource: '../Classes/*'
    exclude: '../Classes/Domain/Model/*'
  
  UniversityOfCopenhagen\kuRecentContentBackendModule\Controller\RecentContentController:
      tags: ['backend.controller']
